- name: Deploy to Vercel
  uses: amondnet/vercel-action@master
  env:
    VERSION: ${{ env.GITHUB_SHA }}
  with:
    vercel-token: ${{ secrets.VERCEL_TOKEN }}
    vercel-org-id: ${{ secrets.ORG_ID}}
    vercel-project-id: ${{ secrets.PROJECT_ID}}
    working-directory: ./
    vercel-args: '--prod' # 可不填
